# This is NOT meant to be used in projects! It only tests the starzel-buildout.
language: python
sudo: false
cache:
  pip: true
  directories:
  - eggs
  - downloads
python:
  - 2.7
before_install:
  - echo "[variables]" > $HOME/mrbob_answers.txt
  - echo "package.type = Basic" >> $HOME/mrbob_answers.txt
  - echo "package.namespace = project" >> $HOME/mrbob_answers.txt
  - echo "package.namespace2 =" >> $HOME/mrbob_answers.txt
  - echo "package.name = site" >> $HOME/mrbob_answers.txt
  - echo "package.description = A Dummy package" >> $HOME/mrbob_answers.txt
  - echo "package.git.init = n" >> $HOME/mrbob_answers.txt
  - echo "author.name = Philip Bauer" >> $HOME/mrbob_answers.txt
  - echo "author.email = bauer@starzel.de" >> $HOME/mrbob_answers.txt
  - echo "author.github.user = pbauer" >> $HOME/mrbob_answers.txt
  - echo "author.irc = irc.freenode.org#plone" >> $HOME/mrbob_answers.txt
  - echo "plone.version = 5.1.1" >> $HOME/mrbob_answers.txt

install:
  - virtualenv -p `which python` .
  - ln -s local_develop.cfg local.cfg
  - echo -e "[buildout]\nlogin = admin\npassword = admin" > secret.cfg
  - bin/pip install -r requirements.txt
  - pip install mr.bob
  - pip install bobtemplates.plone==3.2.0
  - bin/buildout -N buildout:download-cache=downloads code-analysis:return-status-codes=True annotate

script:
  - bin/buildout -N buildout:download-cache=downloads code-analysis:return-status-codes=True
# create a package 'project.site' using bobtemplates.plone using mrbob_answers.txt
  - mkdir src
  - mrbob -O src/project.site --config $HOME/mrbob_answers.txt bobtemplates.plone:addon
# add that package to buildout.cfg in eggs, testeggs, auto-checkout and [sources]
  - sed -i "15i \    project.site" buildout.cfg
  - sed -i "19i \    project.site [test]" buildout.cfg
  - sed -i "23i \    project.site" buildout.cfg
  - sed -i "29i project.site = fs project.site full-path=\${buildout\:directory}/src/project.site" buildout.cfg
# re-run buildout
  - bin/buildout -N buildout:download-cache=downloads code-analysis:return-status-codes=True
# run tests with the new package using coverage
  - bin/coverage-test
